### PR TITLE
Fixes issue when creating events on iOS17

### LINKED ISSUE #135: Not creating calendar event in iOS 17
After upgrade to iOS 17, I'm unable to add an event to calendar.
In Xcode console shows error `XPC connection was invalidated`

Code Example:

```dart
calendar.Add2Calendar.addEvent2Cal(calendar.Event(
                              title: "Teste",
                              startDate: DateTime.now(),
                              endDate: DateTime.now().add(Duration(hours: 2)),
                              allDay: false,
                              iosParams: const calendar.IOSParams(
                                  reminder: Duration(days: 1)),
                              description: "Evento de teste"));
```

I tried to add the code below, but didn't work.

```
<key>NSCalendarsFullAccessUsageDescription</key>
<string>O aplicativo precisa acessar seu calendário para salvar as agendas</string>
```

Flutter version 3.13.4
Dart version 3.1.2.

### PR DESCRIPTION
**Pull request by mauricioluz**
Fixes issue when creating events on iOS 17.

Resolves #135

### CODE REVIEW

**Review by diegogarciar — APPROVED** [review]
+10 thank you!

**Comment by JmyW** [comment]
Please refer the following error message I got on 2.2.5. It's passed when I roll back to 2.2.4.
@mauricioluz Have you tried this version? Are you seeing the same?

============================
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':add_2_calendar:compileDebugJavaWithJavac'.
error: invalid source release: 17

**Comment by diegog-sf** [comment]
It worked for me when I tested, does the example app work for you? Can you try executing flutter clean?

**Comment by JmyW** [comment]
Yes. I did the flutter clean, not helpful.

Further found, I can successfully compile on my Mac PC.
The failure is only happened on my Windows PC.

**Comment by JmyW** [comment]
The root cause is the version of JDK. I upgrade from 12 to 17, it's fixed. Thanks!

**Pull request merged**
