### PR TITLE
added recurring event android RRULE

### PR DESCRIPTION
**Pull request by andraskende**
Hello,

This code is working fine on my local finally :)

Looks like the calendar API its very picky as there are some requirements like based on my testing:

allDay enabled:
-  needs the startDate and endDate in UTC.
-  with androidNoUI: true needs:  timeZone: 'UTC'.
-  with androidNoUI: false do not specify timeZone.

rRule enabled with androidNoUI: true:
- unset CalendarContract.Events.DTEND
- set CalendarContract.Events.DURATION

some rules tested:
        rRule: 'FREQ=WEEKLY',
        rRule: 'FREQ=MONTHLY',
        rRule: 'FREQ=YEARLY',

Please test :)

Best regards,
Andras

androidNoUI: false

    final cal.Event event = cal.Event(
        title: 'test title',
        description: 'Test description',
        startDate: DateTime.utc(year, month, day, 0, 0, 0),
        endDate: DateTime.utc(year, month, day, 0, 0, 0),
        allDay: true,
        rRule: 'FREQ=YEARLY',
    );
    cal.Add2Calendar.addEvent2Cal(event, androidNoUI: false);

androidNoUI: true

    final cal.Event event = cal.Event(
        title: 'test title',
        description: 'Test description',
        startDate: DateTime.utc(year, month, day, 0, 0, 0),
        endDate: DateTime.utc(year, month, day, 0, 0, 0),
        duration: 'PT1M',
        allDay: true,
        rRule: 'FREQ=YEARLY',
        timeZone: 'UTC',
    );
    cal.Add2Calendar.addEvent2Cal(event, androidNoUI: true);

### CODE REVIEW

**Comment by diegogarciar** [comment]
Thanks, I'll take the opportunity to also add some other features mentioned in other issues so I might take the rest of the week to review it.

**Comment by diegogarciar** [comment]
@andraskende I ended up adding a full implementation that is also compatible with iOS, you can specify the recurrence without using RRULE, and as a fallback you can use it (android only). Could you test it and give me feedback?

**Comment by andraskende** [comment]
just a few things what noticed so far:

I was able to insert with noUI=false

noUI=true gave :

E/flutter (23678): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, column 'android.intent.extra.EMAIL' is invalid, null, java.lang.IllegalArgumentException: column 'android.intent.extra.EMAIL' is invalid

E/MethodChannel#flutter.javih.com/add_2_calendar(24770): java.lang.IllegalArgumentException: column 'android.intent.extra.EMAIL' is invalid


might be related:
https://stackoverflow.com/questions/65941797/adding-emails-to-the-calendar-event-intent-the-emails-do-not-get-populated

worked after commenting out intent EXTRA_EMAIL in Add2CalendarPlugin.java line ~220

    if (invites != null) {
       // values.put(Intent.EXTRA_EMAIL, invites);
    }


Thank you !!!

**Comment by diegogarciar** [comment]
Will you be using the noUI feature?
I now  realize it lacks a lot of functionality. I’m not even getting the calendar Id so I its writing on a random calendar. 

I would need to request read calendar permissions to get ids and names, and even show them to the user to choose if there’s  more than one.

**Comment by andraskende** [comment]
I'm not using the noUI feature. so  these new changes working fine for me.

**Comment by diegogarciar** [comment]
Thanks, I'll remove the noUI feature for now then!

**Pull request merged**
